name: Ultima CI

on:
  push:
    paths-ignore:
      - "*.md"
      - .gitignore
  pull_request:
    types: [opened, reopened]
  schedule:
    - cron: '0 3 */2 * *'

jobs:
  test:
    name: 'Test os=${{ matrix.os }} py=${{ matrix.python-version }}/${{ matrix.architecture}}'
    timeout-minutes: 60
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10']
        include:
          - architecture: 'x64'
            flag-ignore-failure: false
          - os: windows-latest
            python-version: '3.8'
            architecture: 'x86'
          - os: ubuntu-latest
            python-version: '3.8'
            archive-artifacts: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      - name: Build, install and test
        timeout-minutes: 15
        shell: bash
        env:
          USE_INTERNAL_CODE: "false"
        run: ./ci.sh
        continue-on-error: ${{ matrix.flag-ignore-failure }}
      - name: Archive library
        if: ${{ matrix.archive-artifacts }}
        uses: actions/upload-artifact@v3
        with:
          name: library
          path: dist/*.zip
      - name: Archive code coverage results
        if: ${{ matrix.archive-artifacts }}
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: workdir/cov_html.zip
